#!/bin/bash
touch scanned
for ip in 192.168.{1,2,16,17}.{1..254}; do
  ping -c 1 -W 1 $ip | grep -q "64 bytes" && echo $ip >> scanned & 
 # echo $ip > scanned
done

clear
cat /home/kubh/geeknepal/scanned
#for ip in 192.168.16.{1..255}; do  # for loop and the {} operator
 #   ping -c 1  $ip > /dev/null 2> /dev/null  # ping and discard output
  #  if [ $? -eq 0 ]; then  # check the exit code
   #     echo "${ip} is up" # display the output
        # you could send this to a log file by using the >>pinglog.txt redirect
    #else
     #   echo "${ip} is down"
    #fi
#done
